### ISSUE TITLE
Add support Proxy 

### ISSUE THREAD

**Issue by skvoshiz** [a-legotin/InstaSharper#1]
Hi, do you can add support Proxy (HTTP\HTTPS\Socks4\Socks4a\Socks5) ?
Just without this i need rewrite more code for xNet c# (lib. for Web requests)
I dont know lib. HttpClient, and cant add proxy=(

**Comment by skvoshiz** [comment]
Wow sorry, i dont see https://github.com/a-legotin/InstaSharper/wiki
Do you can show me example?

**Comment by a-legotin** [comment]
Hi, you can implement it like this:

````c#
public class MyProxy : IWebProxy
{
    public Uri GetProxy(Uri destination)
    {
        return new Uri("http://localhost:8888");
    }

    public bool IsBypassed(Uri host)
    {
        return false;
    }

    public ICredentials Credentials { get; set; }
}
```

Hope you will find this helpful
