### ISSUE TITLE
user must be authenticate exception

### ISSUE THREAD

**Issue by EhsanArio** [a-legotin/InstaSharper#100]
Hi 
I use you example on github but your code returns "user must be authenticated" exception.
Here is some screenshots :

![image](https://user-images.githubusercontent.com/7068483/32964222-bceda22a-cbe7-11e7-94b3-d80a6cb5a1b9.png)

user must be authenticated" exception
![image](https://user-images.githubusercontent.com/7068483/32964338-250494c2-cbe8-11e7-96b3-8789050d63dd.png)

User and pass are correct.

Any idea ?

**Comment by Sidrav** [comment]
This seem to work for me!
just leave all other at default...

_instaApi = InstaApiBuilder.CreateBuilder()
                .SetUser(userSession)
                .Build();

Hope this helps

**Comment by EhsanArio** [comment]
Hi @Sidrav 

This is result :
"logInResult.Succeeded" is true but "IsUserAuthenticated" is false.

![image](https://user-images.githubusercontent.com/7068483/32978455-c43a986a-cc57-11e7-9012-0d30a2fa1198.png)


![image](https://user-images.githubusercontent.com/7068483/32978458-d01238aa-cc57-11e7-9d46-334a236aeee6.png)


Any Help ?

**Comment by a-legotin** [comment]
@EhsanArio , provide some logs first.

**Comment by EhsanArio** [comment]
How can I generate logs ?

**Comment by a-legotin** [comment]
Specify debug logger when building Api instance.
`.UseLogger(new DebugLogger(LogLevel.All)) `

**Comment by EhsanArio** [comment]
Ok
But where the log file saves ?

On Nov 18, 2017 21:32, "Alexander Legotin" <notifications@github.com> wrote:

Specify debug logger when building Api instance.
.UseLogger(new DebugLogger(LogLevel.All))

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/a-legotin/InstaSharper/issues/100#issuecomment-345459405>,
or mute the thread

**Comment by EhsanArio** [comment]
Ok

this is code :

` var device =AndroidDeviceGenerator.GetRandomAndroidDevice();
                var requestMessage = ApiRequestMessage.FromDevice(device);
                _instaApi = InstaApiBuilder.CreateBuilder()
                    .SetUser(userSession)
                    .SetApiRequestMessage(requestMessage)
                    .UseLogger(new DebugLogger(LogLevel.All)) // use logger for requests and debug messages
                    .SetRequestDelay(TimeSpan.FromSeconds(2))
                    .Build();
                Console.WriteLine($"Logging in as {userSession.UserName}");
                var logInResult = await _instaApi.LoginAsync();`

and get "user must be authenticate exception" at "var logInResult = await _instaApi.LoginAsync();"

Here is screenshot :

![image](https://user-images.githubusercontent.com/7068483/32984046-d184ef32-ccb3-11e7-8c16-d6f32b4ff8a1.png)


But if i use this code and set "requestMessage" to null :

`                _instaApi = InstaApiBuilder.CreateBuilder()
                    .SetUser(userSession)
                    .SetApiRequestMessage(null)
                    .UseLogger(new DebugLogger(LogLevel.All)) // use logger for requests and debug messages
                    .SetRequestDelay(TimeSpan.FromSeconds(2))
                    .Build();`

I didn't get that exception there but in other location
Here is log :

> Starting demo of InstaSharper project
Logging in as InstaShrper007
10:59 ب.ظ:      Request: https://i.instagram.com/
10:59 ب.ظ:      Response: GET https://www.instagram.com/
10:59 ب.ظ:      Content:
10:59 ب.ظ:      got html content!
10:59 ب.ظ:      Response: GET https://www.instagram.com/
10:59 ب.ظ:      Content:
10:59 ب.ظ:      got html content!
10:59 ب.ظ:      ----------------------------------------------------------------------------------------------------
10:59 ب.ظ:      Request: POST https://i.instagram.com/api/v1/accounts/login/
10:59 ب.ظ:      Headers:
10:59 ب.ظ:      Accept-Language:["en-US"]
10:59 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
10:59 ب.ظ:      X-IG-Connection-Type:["WIFI"]
10:59 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
10:59 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "77395489-d349-491d-accc-6ab4e8deedf6",
  "signed_body": "7021b7640882bb3a5ab82050c044a6616b115dfc8a29a9169189ea25f6445d85.{\"phone_id\":\"9ade42fb-09de-4931-8526-8f7c1bd3ce2a\",\"username\":\"InstaShrper007\",\"guid\":\"505cbe9d-487c-49d4-8f2c-b1cc166d1094\",\"device_id\":\"android-6ca17858bca39f49\",\"password\":\"1q!Q2w@W\",\"login_attempt_count\":\"0\"}",
  "ig_sig_key_version": "4"
}
10:59 ب.ظ:      Response: POST https://i.instagram.com/api/v1/accounts/login/
10:59 ب.ظ:      Content:
10:59 ب.ظ:      {"logged_in_user": {"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://scontent-frt3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true, "is_business": false, "can_see_organic_insights": false, "show_insights_terms": false, "allow_contacts_sync": false, "phone_number": ""}, "status": "ok"}
Press 1 to start basic demo samples
Press 2 to start upload photo demo sample
Press 3 to start comment media demo sample
Press 4 to start stories demo sample
Press 5 to start demo with saving state of API instance
Press 6 to start messaging demo sample
1
System.ArgumentException: user must be authenticated
   at InstaSharper.API.InstaApi.ValidateLoggedIn()
   at InstaSharper.API.InstaApi.<GetCurrentUserAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InstaSharper.Examples.Samples.Basics.<DoShow>d__3.MoveNext() in C:\Users\Admin\Desktop\InstaSharper\InstaSharper.Examples\Samples\Basics.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at InstaSharper.Examples.Program.<MainAsync>d__2.MoveNext() in C:\Users\Admin\Desktop\InstaSharper\InstaSharper.Examples\Program.cs:line 84

Unhandled Exception: System.ArgumentException: user must be authenticated
   at InstaSharper.API.InstaApi.ValidateLoggedIn()
   at InstaSharper.API.InstaApi.<LogoutAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InstaSharper.Examples.Program.<MainAsync>d__2.MoveNext() in C:\Users\Admin\Desktop\InstaSharper\InstaSharper.Examples\Program.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InstaSharper.Examples.Program.Main(String[] args) in C:\Users\Admin\Desktop\InstaSharper\InstaSharper.Examples\Program.cs:line 22

**Comment by a-legotin** [comment]
**Why do you need custom request message?**
Use following code to login and run, then send logs:

```
var userSession = new UserSessionData
                {
                    UserName = "user",
                    Password = "pass"
                };
                _instaApi = InstaApiBuilder.CreateBuilder()
                    .SetUser(userSession)
                    .UseLogger(new DebugLogger(LogLevel.All)) 
                    .SetRequestDelay(TimeSpan.FromSeconds(2))
                    .Build();
                var logInResult = await _instaApi.LoginAsync();
```

**Comment by a-legotin** [comment]
Okay, found a problem. I suggest you use lowercase for username in session data. But, will be corrected in future versions.
