### ISSUE TITLE
Unknown Exception while getting Follower and Following

### ISSUE THREAD

**Issue by EhsanArio** [a-legotin/InstaSharper#103]
Hi
This is screenshot :

![image](https://user-images.githubusercontent.com/7068483/33162799-b5ea90d4-d040-11e7-9e74-73766d242782.png)

and this is logs :

> Starting
 demo of InstaSharper project
Logging in as instashrper007
11:21 ق.ظ:      Request: https://i.instagram.com/
11:21 ق.ظ:      Response: GET https://www.instagram.com/
11:21 ق.ظ:      Content:
11:21 ق.ظ:      got html content!
11:21 ق.ظ:      Response: GET https://www.instagram.com/
11:21 ق.ظ:      Content:
11:21 ق.ظ:      got html content!
11:21 ق.ظ:      ---------------------------------------------------------------------------------------------------
11:21 ق.ظ:      Request: POST https://i.instagram.com/api/v1/accounts/login/
11:21 ق.ظ:      Headers:
11:21 ق.ظ:      Accept-Language:["en-US"]
11:21 ق.ظ:      X-IG-Capabilities:["3boBAA=="]
11:21 ق.ظ:      X-IG-Connection-Type:["WIFI"]
11:21 ق.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
11:21 ق.ظ:      Properties:
{
  "X-Google-AD-ID": "d062dacc-d3cd-4728-93b8-27bda4cfa63d",
  "signed_body": "0ecf25f9f9663f7d3b897a6015e0919b539ddb4a719b8de8b71aeea72439ebd8.{\"phone_id\":\"3e90b5f5-23c3-4fd1-b9ba-8e090a1fa397\",\"username\":\"instashrper007\",\"guid\":\"a91cd29b-2070-4c4e-b4cb-35335b2a38dc\",\"device_id\":\"android-0cbd3ed34d2cf71a\",\"password\":\"1q!Q2w@W1\",\"login_attempt_count\":\"0\"}",
  "ig_sig_key_version": "4"
}
11:21 ق.ظ:      Response: POST https://i.instagram.com/api/v1/accounts/login/
11:21 ق.ظ:      Content:
11:21 ق.ظ:      {"logged_in_user": {"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://instagram.fdel3-1.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true, "is_business": false, "can_see_organic_insights": false, "show_insights_terms": false, "allow_contacts_sync": false, "phone_number": ""}, "status": "ok"}
Press 1 to start basic demo samples
Press 2 to start upload photo demo sample
Press 3 to start comment media demo sample
Press 4 to start stories demo sample
Press 5 to start demo with saving state of API instance
Press 6 to start messaging demo sample
1
11:21 ق.ظ:      ---------------------------------------------------------------------------------------------------
11:21 ق.ظ:      Request: POST https://i.instagram.com/api/v1/accounts/current_user?edit=true
11:21 ق.ظ:      Headers:
11:21 ق.ظ:      Accept-Language:["en-US"]
11:21 ق.ظ:      X-IG-Capabilities:["3boBAA=="]
11:21 ق.ظ:      X-IG-Connection-Type:["WIFI"]
11:21 ق.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
11:21 ق.ظ:      Properties:
{
  "X-Google-AD-ID": "d062dacc-d3cd-4728-93b8-27bda4cfa63d"
}
11:21 ق.ظ:      Response: POST https://i.instagram.com/api/v1/accounts/current_user/?edit=true
11:21 ق.ظ:      Content:
11:21 ق.ظ:      {"user": {"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://instagram.fnag1-2.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true, "biography": "", "external_url": "", "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "https://instagram.fnag1-2.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"}, {"width": 640, "height": 640, "url": "https://instagram.fnag1-2.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"}], "hd_profile_pic_url_info": {"url": "https://instagram.fnag1-2.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "width": 150, "height": 150}, "show_conversion_edit_entry": true, "birthday": null, "phone_number": "", "gender": 3, "email": "instashrper007@gmail.com", "can_link_entities_in_bio": false, "max_num_linked_entities_in_bio": 5}, "status": "ok"}
Logged in: username - instashrper007, full name - Insta
11:22 ق.ظ:      ----------------------------------------------------------------------------------------------------
11:22 ق.ظ:      Request: GET https://i.instagram.com/api/v1/users/search?q=instashrper007
11:22 ق.ظ:      Headers:
11:22 ق.ظ:      Accept-Language:["en-US"]
11:22 ق.ظ:      X-IG-Capabilities:["3boBAA=="]
11:22 ق.ظ:      X-IG-Connection-Type:["WIFI"]
11:22 ق.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
11:22 ق.ظ:      Properties:
{
  "X-Google-AD-ID": "d062dacc-d3cd-4728-93b8-27bda4cfa63d",
  "timezone_offset": "43200",
  "count": "1",
  "rank_token": "6462369763_3e90b5f5-23c3-4fd1-b9ba-8e090a1fa397"
}
11:22 ق.ظ:      Response: GET https://i.instagram.com/api/v1/users/search/?q=instashrper007
11:22 ق.ظ:      Content:
11:22 ق.ظ:      {"num_results": 1, "users": [{"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://scontent-nrt1-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "friendship_status": {"following": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "is_verified": false, "has_anonymous_profile_picture": true, "follower_count": 1, "byline": "1 follower", "mutual_followers_count": 0.0}], "has_more": false, "rank_token": "ae0ce09a-7d29-4ec7-b7db-ec541fef23dd", "status": "ok"}
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at InstaSharper.API.InstaApi.<GetUserFollowersAsync>d__22.MoveNext()
Stacktrace:    at InstaSharper.API.InstaApi.<GetUserFollowersAsync>d__22.MoveNext()

**Comment by EhsanArio** [comment]
in this log it shows 1 follower exists.
Any help to get its name ?

**Comment by a-legotin** [comment]
fixed in 1.4.13

**Comment by EezeSolutions** [comment]
@a-legotin 
I just tired the work around but same exception ...
![screenshot 2018-01-26 10 56 45](https://user-images.githubusercontent.com/17122621/35426604-0d9c41ca-0286-11e8-9740-65ccb992e815.png)
