### ISSUE TITLE
Request for Video Uploads.

### ISSUE THREAD

**Issue by Examed** [a-legotin/InstaSharper#105]
You have an awesome SDK here. Its super easy to use. :)
The only thing I'm missing is the option to upload a Video to "INSTAGRAM STORYS".

It wold be awesome if you can add that option 👍 
Thank you
Gereon

**Comment by a-legotin** [comment]
Hello @Examed , I will have a look at this feature at near future. Thanks.

**Comment by Yigityakut** [comment]
Hi, It has been almost 3 months after your message about 'near future' and I would like to know if there is an improvement about the feature we need? Sorry if I look demanding and appreciate the code you wrote. Thank you in advance

**Comment by a-legotin** [comment]
no ETA, sorry

**Comment by Yigityakut** [comment]
InstaImage class has just height weight and the uri. Is it possible to get the image itself and not the uri ? I will also ask this question for videos. Can't we get the file itself and not the uri ?

**Comment by a-legotin** [comment]
@Yigityakut  you should download images yourself.

**Comment by Yigityakut** [comment]
@a-legotin It is easy to download image no problem for that, but when we use getmedia functions, if the media is a video, is there no way to get the video ? Because for the video link you return for us, only gives the thumbnail image of the video. How can we achieve to get video itself ?

**Comment by Nanosync** [comment]
Use the InstaMedia.Videos[].Url property to obtain a video url for downloading.

**Comment by Yigityakut** [comment]
@Nanosync InstaMedia class doesn't have a property like Videos[].

`    public class InstaMedia
    {
        public InstaMedia();

        public bool IsMultiPost { get; }
        public bool HasAudio { get; set; }
        public int ViewCount { get; set; }
        public InstaCarousel Carousel { get; set; }
        public InstaUserShortList Likers { get; set; }
        public List<InstaUserTag> Tags { get; set; }
        public bool HasLiked { get; set; }
        public bool PhotoOfYou { get; set; }
        public string CommentsCount { get; set; }
        public InstaCaption Caption { get; set; }
        public string NextMaxId { get; set; }
        public int LikesCount { get; set; }
        public string TrakingToken { get; set; }
        public InstaUser User { get; set; }
        public string Height { get; set; }
        public int Width { get; set; }
        public List<InstaImage> Images { get; set; }
        public string FilterType { get; set; }
        public string ClientCacheKey { get; set; }
        public string Code { get; set; }
        public InstaMediaType MediaType { get; set; }
        public DateTime DeviceTimeStap { get; set; }
        public string InstaIdentifier { get; set; }
        public string Pk { get; set; }
        public DateTime TakenAt { get; set; }
        public List<InstaComment> PreviewComments { get; set; }
        public InstaLocation Location { get; set; }
    }`

**Comment by Nanosync** [comment]
@Yigityakut You will have to use the version from the develop branch as it is not on master yet.

**Comment by Yigityakut** [comment]
@Nanosync I am using the lastest release 1.4.0 . Should I download the project from develop branch and compile it and use the new dll ?

**Comment by Nanosync** [comment]
@Yigityakut You can obtain it from the myget feed.

**Comment by Yigityakut** [comment]
@Nanosync Thank you. I achieved to get the video itself from the getmedia method. In your fork, did you manage to upload videos also?

**Comment by Startname** [comment]
@Yigityakut  @Nanosync 
I could not download of myget feed.
Can you give me dll?
Thankful.

**Comment by a-legotin** [comment]
@Startname  why you cant download [myget](https://www.myget.org/feed/Details/instasharper-develop)?

**Comment by Startname** [comment]
@a-legotin When i open it  https://www.myget.org/feed/Details/instasharper-develop
redirect to https://www.myget.org/

**Comment by a-legotin** [comment]
ya, thats correct - you must login

**Comment by Startname** [comment]
@a-legotin  I have an account in myget
and I'm logged in.
but link redirect to https://www.myget.org/
Can you give me Latest version dll?

**Comment by a-legotin** [comment]
implemented
