### ISSUE TITLE
Instagram Return Fake Detail !?

### ISSUE THREAD

**Issue by momenimohammad23** [a-legotin/InstaSharper#11]
Hi 
Thank for this awsome project .
I test it , but when i want to get  users media allways mediaResponse.MoreAvailable is true
for example for user "mohammadq74" i want to get max 5 page , it return 73 media while this user just have 37 media ! 
i use this code 
var currentUserMedia = _instaApi.GetUserMedia("mohammadq74", 5);

excuse me for bad english :)

**Comment by a-legotin** [comment]
Hello @momenimohammad23 , what version you are using?

**Comment by momenimohammad23** [comment]
@a-legotin  "version": "1.2.2"

**Comment by a-legotin** [comment]
got it reproduced, will be fixed in  1.3.3
