### ISSUE TITLE
I can now only get the last direct message sent in a conversation. (GetDirectInboxAsync)

### ISSUE THREAD

**Issue by draxpc** [a-legotin/InstaSharper#116]
When checking the JSON returned from GetDirectInboxAsync, I can only retrieve the last message in a conversation / the last item.

Also, I did not have this problem earlier today. This has just started happening an hour ago.

![image](https://user-images.githubusercontent.com/13519960/34074678-4b318cf6-e2ac-11e7-99ed-e00802be2dee.png)

Version: 1.3.8

Thank you!

**Comment by a-legotin** [comment]
Just checked and working fine, if you get json from Instagram with only one message I cannot do anything about it.
