### ISSUE TITLE
How to get mediaId of uploaded media?

### ISSUE THREAD

**Issue by mehrdad079** [a-legotin/InstaSharper#117]
Hi
thanks for great project
i need to get MediaId of uploaded media, so i can store it in my database for further operations like edit and delete!

as supposed in api, the function UploadPhotoAsync() should return InstaMedia, which has InstaCaption and also it has MediaId!:
accessing path to variable : InstaMedia.Caption.MediaId
but always UploadPhotoAsync() return null value with success = true flag!

so please help me how to get that MediaId

my only possible way at this moment is to call GetUserMediaAsync() immediatly after uploading and get first InstaMedia which is newest uploaded media!

thanks in advance.

**Comment by a-legotin** [comment]
fixed in 4d17b99e27dbd4e759283602f75319f15cfd5f4c
