### ISSUE TITLE
Registration on Instagram

### ISSUE THREAD

**Issue by Lorymi** [a-legotin/InstaSharper#118]
Hello.
Is it possible to add the registration method to the Instagram? in InstaSharper?

**Comment by aopiskin** [comment]
Hi Yes it is possible

**Comment by a-legotin** [comment]
Hello @alish123456, it will not be implemented in near future.

**Comment by a-legotin** [comment]
@Startname , i dont see any real need in this function. You can register new account using the web site or official app.

**Comment by alish123456** [comment]
@Startname i use [Instagram Account Creator](https://github.com/kronoscloud/Instagram-Account-Creator) and [InstaCreator](https://github.com/Multiby7e/InstaCreator)  for registration instagram on C# in my app

http://uupload.ir/files/9z2_2313235435.png

If you add this feature to the library InstaSharper, I'm grateful....
and a library Must be complete In every respect..

**Comment by a-legotin** [comment]
implemented
