### ISSUE TITLE
How to login with token instead of username and password?!

### ISSUE THREAD

**Issue by mehrdad079** [a-legotin/InstaSharper#119]
How to get some credentials (like token) after logining with username and password for future login without username and password?
Now for every time i need to use this api i should login with username and password
Is there a way to login with saved token from first login?

Just like instagram app you just enter user password once!

**Comment by a-legotin** [comment]
Have you checked [examples](https://github.com/a-legotin/InstaSharper/blob/develop/InstaSharper.Examples/Samples/SaveLoadState.cs)???
I guess no.
