### ISSUE TITLE
Add own android devices to generator

### ISSUE THREAD

**Issue by cavemanpussy** [a-legotin/InstaSharper#125]
Hey guys!

I've been using this API-Implementation for a few days and it works pretty well!
Now I'm wondering if it's possible to add some extra android devices e.g. my own Xiaomi Redmi.
Over some apps I managed to find out the relevant parameters as mentioned in the originally class.
But where can I get the DeviceGuid and the PhoneGuid?
Can anyone provide me some information or instruction?

Kind regards and have a nice day!
Matze

**Comment by a-legotin** [comment]
Hello, there is no possibility to add you custom device currently and I dont see any reason why you need that, can you explain?

**Comment by cavemanpussy** [comment]
I'm using the API for some stats concerning followers. I'm afraid that, if more and more people use this API over the same emulated devices, I'll get a ban.

**Comment by a-legotin** [comment]
You anyway will get a ban, just matter of time. Closed.
