### ISSUE TITLE
Get Counts Posts

### ISSUE THREAD

**Issue by Startname** [a-legotin/InstaSharper#128]
how i can get counts posts of GetCurrentUserAsync ??

**Comment by gdupiton** [comment]
@Startname Your question reads very strangely, but I think you're asking if you can get post count from the GetCurrentUserAsync method...?  If so, I don't believe that method will get you what you're looking for.  At a very quick glance, it appears to me that you would have to do something like GetUserMediaAsync(username).Result.Value.Count; (Where the current user's name would be provided as the username in this case...)  If I misinterpreted your question, please forgive me.  But, your question was written in poor grammar.

**Comment by a-legotin** [comment]
@Startname @gdupiton  that's very bad idea. Following code is the best solution in this case:

`            var currentUser = await _instaApi.GetCurrentUserAsync();
            var userinfo = await _instaApi.GetUserInfoByIdAsync(currentUser.Value.Pk);
            var mediaCount = userinfo.Value.MediaCount;
`
