### ISSUE TITLE
Need info regarding UserSessionData

### ISSUE THREAD

**Issue by EezeSolutions** [a-legotin/InstaSharper#130]
If i have the info :

        InstaUserShort uu = new InstaUserShort();
                        uu.UserName = "ABXuSER";
                        
                        var userSession = new UserSessionData
                        {
                            UserName = "ABXuSER",
                            Password = password,
                            CsrfToken = "sometoken",
                            RankToken = "someRank",
                           LoggedInUder=uu,

                        };

Meaning i have the previous session data saved and want to reuse that User without login in again what do i do?

Thank you

**Comment by a-legotin** [comment]
Everything you need is already in the [examples](https://github.com/a-legotin/InstaSharper/blob/develop/InstaSharper.Examples/Samples/SaveLoadState.cs)
