### ISSUE TITLE
Issue while getting followers / following

### ISSUE THREAD

**Issue by EezeSolutions** [a-legotin/InstaSharper#131]
I see there is issue here :

**GetUserFollowersAsync
GetCurrentUserFollowersAsync**

**GetCurrentUserFollowersAsync** this gives error and wont return anything some "Object reference not defined exception"

And **GetUserFollowersAsync** will show followers for anyone except the user being logged in 

Please fix . Thank you

**Comment by EezeSolutions** [comment]
@a-legotin

**Comment by a-legotin** [comment]
Just skip that error and continue loading from last successful next_id

**Comment by EezeSolutions** [comment]
@a-legotin 

This will work :
     var result = _instaApi.GetUserFollowersAsync(username, PaginationParameters.MaxPagesToLoad(3)
    .StartFromId("AQAC8w90POWyM7zMjHWmO9vsZNL_TuLp6FR506_C_y3fUAjlCclrIDI2RdSGvur5UjLrq4Cq7NJN8QUhHG-vpbT6pCLB5X9crDxBOHUEuNJ4fA"));

Just hardcoded the nextID an works every time.

**Comment by a-legotin** [comment]
well, that's strange solution, because you starting from the same page all the time, better if you will keep LAST successful net_id, that's will be better.

**Comment by EezeSolutions** [comment]
@a-legotin  
Works for me cause i need to get first few every few minutes etc. :)
Btw  is the above followers list in any order like Most recent first etc or is it just random and if it is is there a way to get the most recent ?

**Comment by a-legotin** [comment]
Its retrieved from IG services, no sorting is applied, so there is no way to control order of followers.

**Comment by EezeSolutions** [comment]
@a-legotin 
Can we get InstaUserList from "GetUserFollowersAsync" instead of InstaUserShortList and it might have the followed date aswell from which we can sort it for most recent?

**Comment by macir27** [comment]
when I run the code, elonmusk's followers get just 200, but elonmusk have more followers. So I add searchQuery parameter in InstaSharper\API\Processors\UserProcessor.cs line:215 and it is working
old
{
UriCreator.GetUserFollowersUri(user.Value.Pk, _user.RankToken,                            followersResponse.Value.NextMaxId);
}
New
{
UriCreator.GetUserFollowersUri(user.Value.Pk, _user.RankToken, searchQuery,                            followersResponse.Value.NextMaxId);
}

**Comment by EezeSolutions** [comment]
@macir27  update the dll and use this :

 

>  var result = _instaApi.GetUserFollowersAsync(username.ToLower(), PaginationParameters.MaxPagesToLoad(100000)
>                                    .StartFromId(""));
> 
>                                     while (result.Status == TaskStatus.WaitingForActivation)
>                                     { }

Works perfectly fine.

**Comment by a-legotin** [comment]
It seems I can consider that issue resolved.
Closing.
