### ISSUE TITLE
Challenge_Required

### ISSUE THREAD

**Issue by giorgi-abashidze** [a-legotin/InstaSharper#133]
When i'm trying to login i'm getting this message Challenge_Required, how can i fix this? i'm doing login with button click, here is the code:

         private async void button1_ClickAsync(object sender, EventArgs e)
         {
              if (usernameBox.Text.Length > 0 && passwordBox.Text.Length > 0)
              {
                errLabel.Text = "";
                var userSession = new UserSessionData
                {
                    UserName = usernameBox.Text.ToString(),
                    Password = passwordBox.Text.ToString(),                    
                };

                _instaApi = InstaApiBuilder.CreateBuilder()
                   .SetUser(userSession)
                   .UseLogger(new DebugLogger(LogLevel.Exceptions))
                   .SetRequestDelay(TimeSpan.FromSeconds(2))
                   .Build();

                const string stateFile = "state.bin";

                if (File.Exists(stateFile))
                {
                    Stream fs = File.OpenRead(stateFile);
                    fs.Seek(0, SeekOrigin.Begin);
                    _instaApi.LoadStateDataFromStream(fs);

                }

                var logInResult = await _instaApi.LoginAsync();
                if (!logInResult.Succeeded)
                {                
                    errLabel.Text = logInResult.Info.Message;                    
                }
                else {
                    var state = _instaApi.GetStateDataAsStream();
                    using (var fileStream = File.Create(stateFile))
                    {
                        state.Seek(0, SeekOrigin.Begin);
                        state.CopyTo(fileStream);
                    }

                    MainForm mainForm = new MainForm(_instaApi);
                    mainForm.Show();
                }
                                               
            }
            else {
                errLabel.Text = "enter username and pasword";
            }
          
        }

i'm doing something wron?

**Comment by a-legotin** [comment]
login from your app and pass challenge, read [here](https://github.com/a-legotin/InstaSharper/issues/112) and [there](https://github.com/a-legotin/InstaSharper/wiki/FAQ#checkpoint-required).
