### ISSUE TITLE
Send  A Link in Direct Message

### ISSUE THREAD

**Issue by EezeSolutions** [a-legotin/InstaSharper#134]
I am sending this message:

Hello how are you ! 
😁 😂 🤣 😃 😄 😅 😆 😉 
Youtube.com

All the above gets sent perfectly fine but Youtube.com  shows as text not a link. I copy pasted same message on the app an resend it from the app an Youtube.com shows as link .
Any fix to this or explanation .

thank you

**Comment by a-legotin** [comment]
@EezeSolutions sending of a link is not implemented yet.

**Comment by EezeSolutions** [comment]
@a-legotin 
If you can guide me to the correct way i can add it myself if it needs to be something set in the httprequest...?

**Comment by a-legotin** [comment]
@EezeSolutions, yeah sure, contact me on telegram.
