### ISSUE TITLE
Real time comments subscription

### ISSUE THREAD

**Issue by pesar368** [a-legotin/InstaSharper#136]
Hello Guys.
Is there any way to subscribe to comments in realtime client ? 

how instagram on android gets immediate notifications about comments?

maybe instagram use GCM  - https://developers.google.com/cloud-messaging/
or FCM
the question is - how we can hook in to it and get those comment notifications?

Thanks.

**Comment by pesar368** [comment]
I Found Instagram Api written-in PHP : 
https://github.com/mgp25/Instagram-API/pull/1459#issuecomment-324904341

but I don't understand it

**Comment by a-legotin** [comment]
@pesar368 any platform related features (including push notifications support) will not be implemented in my library

**Comment by valga** [comment]
@a-legotin Facebook is big enough to have its own Push notifications service called FBNS. It is platform independent, and it uses custom MQTT protocol as a transport one. JFYI.
