### ISSUE TITLE
Receiving Null Reference from Proxy

### ISSUE THREAD

**Issue by BillChirico** [a-legotin/InstaSharper#137]
Hello,

I am trying to connect to Instagram using a proxy. When I receive a response the content is null.

**Comment by a-legotin** [comment]
Provide logs.(Check out how to create issues)[https://github.com/a-legotin/InstaSharper/wiki/Creating-issues-guideline-(template)]

**Comment by a-legotin** [comment]
Doesn't sounds like important for the reporter, no action in two weeks.
Closing for now.
