### ISSUE TITLE
Not Null Caption Became Null after Upload Image

### ISSUE THREAD

**Issue by zerodwide** [a-legotin/InstaSharper#140]
Hi Guys

i was able to successfully upload image with caption
but today i saw that still i can upload image but the caption will become empty!
i am not spamming and using safe ip
still i can rename caption or upload image with caption on my phone

please help

thanks in advance

**Comment by etaxi341** [comment]
Is it possible that you are using to many tags in your caption? Instagram doesnt allow more than I think 20 tags in a caption

**Comment by zerodwide** [comment]
Thanks for anwer

No, just plain text
Even i created another account with mobile, but faced same result ;(

I have to mention i am using last release of instasharper in nuget

Is any important changes made?
Why with just working version suddenly this thing happened?

**Comment by a-legotin** [comment]
Provide logs and test project, read wiki for more details

**Comment by zerodwide** [comment]
The issue has been solved by no change!

I think there was a limit by default android device spec which was banned for a while , because i changed ip and account but still no caption!

Again i should clearify that only sent about 500 posts in a week with about 100 hashtags (each post max only one hashtag) and all was sent manualy , not atomatic fast posting!
