### ISSUE TITLE
InstaSharper checkpoint_required Instagram Private API (mobile)

### ISSUE THREAD

**Issue by deype0** [a-legotin/InstaSharper#146]
If you get **checkpoint_required** - means this IG services detected unusual activity from your account and don't trust that you are Owner of account. You need to prove that. Try to do:

Login to IG website and pass checkpoint.
Login on your mobile device using official app.
You must use the same IP address as you used to pass checkpoint.
Possibility to pass checkpoint automatically, using this library, will not be implemented.

Did someone implement it?

**Comment by deype0** [comment]
There is one other way, just temporary remove you Instagram account. It's worked from me. https://www.gramto.com/article/how-to-bypass-instagram-checkpoint/

**Comment by a-legotin** [comment]
@deype0 passing of checkpoints will not be added in the library.
