### ISSUE TITLE
Forget Password Account

### ISSUE THREAD

**Issue by Startname** [a-legotin/InstaSharper#150]
hello
Is it possible to Recovery the password in this library?
Thanks

**Comment by a-legotin** [comment]
Hi, its not possible to recover the password using my library.

**Comment by Startname** [comment]
@a-legotin  Thanks...
Will you add this in the future?
and Also get live videos?

I need these two.

**Comment by a-legotin** [comment]
@Startname active development postponed, no new features will be added for now.
