### ISSUE TITLE
Uploading Videos not Photos

### ISSUE THREAD

**Issue by Yigityakut** [a-legotin/InstaSharper#151]
I believe it would be way better if we could upload also videos. I dug the code but I couldn't manage how I can achieve this feature. In mediaprocessor class there is a line where you add ,jpg to end of the file.
`                requestContent.Add(imageContent, "photo", $"pending_media_{ApiRequestMessage.GenerateUploadId()}.jpg");`

Can we change it to mp4 format and see how it works ?

**Comment by a-legotin** [comment]
Will be implemented with #105, search before posting duplicated issues.
