### ISSUE TITLE
Get user medias before specific media

### ISSUE THREAD

**Issue by Marjani** [a-legotin/InstaSharper#155]
Hi again
It's better to be sure of the correct answer before closing the issue!

How can I get all user's medias before specific media?
this argument 
`PaginationParameters.MaxPagesToLoad(int.MaxValue).StartFromId("xxx")`
return a specific media and later...

I want from last media to specific media?

**Comment by a-legotin** [comment]
Investigate [Demo samples](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples), [Tests project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Tests/Endpoints) and [Wiki page](https://github.com/a-legotin/InstaSharper/wiki/How-to-use-library-features) before posting questions! Most of the questions are already answered.
