### ISSUE TITLE
get detail of user in linux .net core

### ISSUE THREAD

**Issue by mybmw123** [a-legotin/InstaSharper#156]
i want to use GetUserInfoByIdAsync method , 
but i think in .net core version this option is not available !

**Comment by a-legotin** [comment]
Why do you think so?
Just checked and this method is available for .netstandart 2.0, and .net framework as well, you should check if you target correct framework.

**Comment by mybmw123** [comment]
![screenshot from 2018-02-18 13-57-14](https://user-images.githubusercontent.com/36584497/36373660-fe6928fa-1525-11e8-99ec-3fed4621586e.png)

**Comment by a-legotin** [comment]
use latest version from MYGET
