### ISSUE TITLE
Unable to Load the Project Into VisualStudio2015

### ISSUE THREAD

**Issue by gowrishankarvgs** [a-legotin/InstaSharper#158]
I downloaded file and when i open it in vs2015, I'm getting error like 'One or More Projects in the solution were not loaded correctly'

**Comment by Marjani** [comment]
I think you should use VS 2017

**Comment by gowrishankarvgs** [comment]
Ok thanks! does this project provide any documentation to understand the code flow.

**Comment by a-legotin** [comment]
@gowrishankarvgs yes it does [Demo samples](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples), [Tests project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Tests/Endpoints) and [Wiki page](https://github.com/a-legotin/InstaSharper/wiki/How-to-use-library-features).
