### ISSUE TITLE
album

### ISSUE THREAD

**Issue by Ahmadreza-s** [a-legotin/InstaSharper#16]
how can we get media that contains multiple photo or video (album)?
i think u should change instagram version

**Comment by a-legotin** [comment]
not yet implemented

**Comment by Ahmadreza-s** [comment]
i cann't wait for next versions.
could you give me some help to implement it for my self?

**Comment by a-legotin** [comment]
dont think so, I can suggest you to fork this repo and start from some coding, in case of any concrete questions welcome to out telegram chanel (can be found in readme). I will try to prepare some guidelines for contributors. Issues is not a place for such discussions, closed.
