### ISSUE TITLE
Failed to Login 

### ISSUE THREAD

**Issue by gowrishankarvgs** [a-legotin/InstaSharper#162]
When i enter Username and Password,I'm getting this error "Unable to login: An error occurred while sending the request".

**Comment by a-legotin** [comment]
check [Demo samples](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples), [Tests project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Tests/Endpoints) and [Wiki page](https://github.com/a-legotin/InstaSharper/wiki/How-to-use-library-features) and add some logs, paste your code here.

**Comment by a-legotin** [comment]
closed due to lack of info from reporter
