### ISSUE TITLE
State.Bin

### ISSUE THREAD

**Issue by gowrishankarvgs** [a-legotin/InstaSharper#163]
What is the use of State.Bin folder and what does it contain ?

**Comment by a-legotin** [comment]
@gowrishankarvgs check [Demo samples](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples), [Tests project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Tests/Endpoints) and [Wiki page](https://github.com/a-legotin/InstaSharper/wiki/How-to-use-library-features) before posting questions.
