### ISSUE TITLE
[Code] Function that login ig with facebook account

### ISSUE THREAD

**Issue by MichaelVanHouHei** [a-legotin/InstaSharper#164]
i have been written a function that login ig with facebook account two years ago(and ig private api) , hope this would be helpful to your project 
getting this link 
// POST accounts/login/ajax/facebook/ --- this for login facebok 
// ALL IG REQUESTS X-CSRFToken is needed
------------------------------------here [GET] this link , and get the "CODE" from ResponseUrl
######## is the client id  
https://www.facebook.com/connect/ping?client_id=#############&domain=www.instagram.com&origin=1&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df2e83b5b6dc3c08%26domain%3Dwww.instagram.com%26origin%3Dhttps%253A%252F%252Fwww.instagram.com%252Ff77076518ca9c%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey
//Get Code From ResponseUrl 
Regex : @"signed_request\=([^\""""]+)"   
----------------------------LINK IG ACCOUNT FROM FACEBOOK--------------------------------
At IG USER cookieContainer 
  IGuser.cookieContainer .Add(new Cookie("fbm_#############&", "base_domain=.instagram.com")
            {
                Domain = new Uri("https://www.instagram.com/").Host
            });
            IGuser.cookieContainer .Add(new Cookie("fbsr_#############&", code.Substring(0, code.IndexOf("&")))
            {
                Domain = new Uri("https://www.instagram.com/").Host
            });
POST   /accounts/fb_linked_account/    --- at ig link 
// Done , By login the facebook account , it will login ig 
------------------------------------------------------------------------------------------------------------

**Comment by MichaelVanHouHei** [comment]
In a nutshell 
-----------------------------------FACEBOOK.COM-------------------------------------------
POST /login.php?login_attempt=1&lwv=110  LoginFacebook
GET GET /connect/ping?client_id=#######################&domain=www.instagram.com&origin=1&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df2e83b5b6dc3c08%26domain%3Dwww.instagram.com%26origin%3Dhttps%253A%252F%252Fwww.instagram.com%252Ff77076518ca9c%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey 
The responseUrl should be something like this :https://staticxx.facebook.com/connect/xd_arbiter.php
and you have to get the "signed_request" parameter from this Url 
------------------------------------https://www.instagram.com----------------------------------------
After That , add the "signed_request" Code to the CookieContainer 
HERE " username and password " is not required , because you have logined facebook and get the signed_request Code 
Requests the following with "X-CSRFTOKEN" & "COOKIECONTAINER" 
COOKIECONTAINER SHOULD HAVE 
ig_vw  , ig_pr , rur , csrftoken , mid , fbm_#################  , ###############
POST /accounts/login/ajax/facebook/
POST accounts/fb_linked_account/
after this requests , u will get the JSON response should be link this 
{
	"fb_linked_account": {
		"profile_pic_url": "https://scontent-hkg3-1.cdninstagram.com/xxxxxxxxxxxxxxxx.jpg",
		"username": "YOUR_IG_NAME"
	},
	"status": "ok"
}
----------------------------------------------------------------------------------------------------------------

**Comment by a-legotin** [comment]
create pull requests instead of pasting some new features in the issues section
