### ISSUE TITLE
liking photo

### ISSUE THREAD

**Issue by Ahmadreza-s** [a-legotin/InstaSharper#17]
hello again

do u know why give me this error? : 
{"message": "Please update your Instagram app to continue liking photos", "status": "fail"}

this is my function : 
`var fields = new Dictionary<string, string>
            {
                {"_uuid", _deviceInfo.DeviceGuid.ToString()},
                {"_uid", _user.LoggedInUder.Pk},
                {"_csrftoken", _user.CsrfToken}
            };
            var userFeedUri = UriCreator.GetUnlikeMediaUri(mediaId);
            var request = HttpHelper.GetDefaultRequest(HttpMethod.Post, userFeedUri, _deviceInfo);
            request.Content = new FormUrlEncodedContent(fields); ;
            var response = await _httpClient.SendAsync(request);
            var json = await response.Content.ReadAsStringAsync();
            Debug.WriteLine(json);`

**Comment by a-legotin** [comment]
Hellow, request created wrongly, fixed in next version
