### ISSUE TITLE
How to get user login info from browser for instagram private API?

### ISSUE THREAD

**Issue by HakanHakyemez** [a-legotin/InstaSharper#187]
Hello,

I need to enter username and password to use Instagram private API. People will not want to be logged in like this. Do I have a chance to redirect the user to the browser (token etc.) and get his login information from here?

Thanks.

**Comment by a-legotin** [comment]
no way, will not be implemented

**Comment by HakanHakyemez** [comment]
Is it the correct way you do not want the password from the user? Can not we do it differently?

**Comment by a-legotin** [comment]
Any suggestions?
