### ISSUE TITLE
login checkpoint_required fixed ?

### ISSUE THREAD

**Issue by seleyemene** [a-legotin/InstaSharper#188]
How do we proceed to bypass the instagram checkpoint_required problem? I tried proxy with proxy but I did not use proxy again with the problem of checkpoint_required

**Comment by a-legotin** [comment]
Possibility to pass checkpoint automatically, using this library, will not be implemented. See [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ#checkpoint-required)
