### ISSUE TITLE
how to access bio data for my followers

### ISSUE THREAD

**Issue by ahemdalsasfi** [a-legotin/InstaSharper#189]
kindly i want to know how to access bio data for my followers

**Comment by etaxi341** [comment]
Should be found here I think: [GetUserInfoByIdAsync](https://github.com/a-legotin/InstaSharper/blob/1d3c1ac8e76a4a5c5758a4c6e61ccba86c182510/InstaSharper/API/Processors/UserProcessor.cs)

**Comment by a-legotin** [comment]
@ahemdalsasfi see the answer above.
