### ISSUE TITLE
Can not add caption to uploaded photo.

### ISSUE THREAD

**Issue by Just3F** [a-legotin/InstaSharper#190]
When i'm trying to upload photo e.g. by UploadPhotoAsync and put caption there I can not see this caption in instagram post. It works a day ago. But right now its not working.

**Comment by etaxi341** [comment]
Did you use more than 30 hashtags? If thats the case Instagram will still upload the image but delete the caption

**Comment by Just3F** [comment]
I have found the issue. Looks like instagram banned my ip adress for post comments only.
