### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path "/state.bin" is denied.

### ISSUE THREAD

**Issue by marcelocferdeveloper** [a-legotin/InstaSharper#191]
**Before creating issue**
Put `x` marks below to validate what you've done before posting issue.
 
[ x ] I've checked [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)
[ x ] I've checked [wiki page](https://github.com/a-legotin/InstaSharper/wiki)
[ x ] I've examined [examples project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples)
[ x ] I've did search [existing issues](https://github.com/a-legotin/InstaSharper/issues) for similar problems
[x  ] I've understand that issue will be closed and locked if issue related to `checkpoint, challenge, feedback required` or `sentry_block` or `signup_block`- see [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)

I tried to follow the example of SaveLoadState, but I got the exception:

System.UnauthorizedAccessException: Access to the path "/state.bin" is denied.

I am using Xamarin and Android phone.

**Comment by a-legotin** [comment]
You tried to access state.bin file, but access denied. Make sure you have access when accessing files. Or skip state loading.

**Comment by marcelocferdeveloper** [comment]
Sorry. I know that is not a library issue...
Do you know if the mobile phone has this state.bin file ? Why the function to re-login use it ? I didn´t get it.

**Comment by a-legotin** [comment]
Do not save state.bin if you don't understand what it is.

**Comment by marcelocferdeveloper** [comment]
Sorry for all these questions...
But, I am trying to do not Login again after user close the app and reopen. 
If I try:

 _instaApi = InstaApiBuilder.CreateBuilder()
                    .SetUser(userSession)
                    .UseLogger(new DebugLogger(LogLevel.Exceptions)) // use logger for requests and debug messages
                    .SetRequestDelay(delay)
                    .Build();

                if (!_instaApi.IsUserAuthenticated)
                {
                    var stream = _instaApi.GetStateDataAsStream();

                    var anotherInstance = InstaApiBuilder.CreateBuilder()
                        .SetUser(UserSessionData.Empty)
                        .SetRequestDelay(TimeSpan.FromSeconds(2))
                        .Build();

                    anotherInstance.LoadStateDataFromStream(stream);


When I try to anotherInstance.GetCurrentUserAsync() , I get the exception that i Need to Login.

Please, give me a help.

Many thanks.
