### ISSUE TITLE
Account create

### ISSUE THREAD

**Issue by mstrifonov** [a-legotin/InstaSharper#197]
**Describe the issue**
Hi, friend. Can you help me.
I create account with code:

```
var userSession = new UserSessionData
                {
                    UserName = "alenavergie",
                    Password = "msps01110"
                };

                var delay = RequestDelay.FromSeconds(2, 2);
                // create new InstaApi instance using Builder
                _instaApi = InstaApiBuilder.CreateBuilder()
                    .SetUser(userSession)
                    .UseLogger(new DebugLogger(LogLevel.Exceptions)) // use logger for requests and debug messages
                    .SetRequestDelay(delay)
                    .Build();
                //// create account
                var username = userSession.UserName;
                var password = userSession.Password;
                var email = "alenaverjie@yandex.ru";
                var firstName = "Alena";
                var accountCreation = await _instaApi.CreateNewAccount(username, password, email, firstName);
```
accountCreation.Success return True.
But when creating a session, instagram says "Your account has been disabled for violating our terms. Learn how to recover your account."
This method is work? Maybe I make a mistake?

Thank you.

**Target (please complete the following information):**
 - Platform: Windows
 - framework - 4.7.2
 - Version 1.4.80

**Comment by a-legotin** [comment]
Hi @mstrifonov , your account has been blocked by IG, I can not do anything about it.

**Comment by mstrifonov** [comment]
Thanks for the help.
I'd like to clarify. Does this method work for you?
Sorry for my English. I translate via google translate

**Comment by mstrifonov** [comment]
Thank you.
