### ISSUE TITLE
How to add Link in Direct Message

### ISSUE THREAD

**Issue by EezeSolutions** [a-legotin/InstaSharper#205]
**Before creating issue**
Put `x` marks below to validate what you've done before posting issue.
 
[ x ] I've checked [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)
[ x ] I've checked [wiki page](https://github.com/a-legotin/InstaSharper/wiki)
[x  ] I've examined [examples project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples)
[ x ] I've did search [existing issues](https://github.com/a-legotin/InstaSharper/issues) for similar problems
[ x ] I've understand that issue will be closed and locked if issue related to `checkpoint, challenge, feedback required` or `sentry_block` or `signup_block`- see [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)

## Be warned - issue will be closed if none from above is done before posting issue.

**Describe the issue**

How to post a link in Direct Message

**Expected behavior**
The link goes through but its not clickable should be a hyperlink.

**Screenshots**

**Target (please complete the following information):**
 - Platform:Windows
 - Target framework [e.g. netstandard, net452]
 - Version [e.g. 1.4.50]

**Comment by a-legotin** [comment]
Use SendLinkMessage
