### ISSUE TITLE
How to Get Instagram User Gender

### ISSUE THREAD

**Issue by muikka** [a-legotin/InstaSharper#209]
**Before creating issue**
Put `x` marks below to validate what you've done before posting issue.
 
[  ] I've checked [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)
[  ] I've checked [wiki page](https://github.com/a-legotin/InstaSharper/wiki)
[ x ] I've examined [examples project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples)
[ x ] I've did search [existing issues](https://github.com/a-legotin/InstaSharper/issues) for similar problems
[  ] I've understand that issue will be closed and locked if issue related to `checkpoint, challenge, feedback required` or `sentry_block` or `signup_block`- see [FAQ](https://github.com/a-legotin/InstaSharper/wiki/FAQ)

## Be warned - issue will be closed if none from above is done before posting issue.

**Describe the issue**
Hot get instagram user gender

**Comment by etaxi341** [comment]
From yourself with "GetCurrentUserAsync()".
You can only get the gender from your own account. Not from others

**Comment by muikka** [comment]
> From yourself with "GetCurrentUserAsync()".
> You can only get the gender from your own account. Not from others

I know that I can get gender with the current user data. Instagram doesnt share gender of others but i discover a wat that can calculate the gender of the others :)
Thanks bro :)

**Comment by muikka** [comment]
@etaxi341 Analyse FullName Bro.
People usually put the real name in this area.
