### ISSUE TITLE
Send a Direct Message

### ISSUE THREAD

**Issue by marcelinhovt** [a-legotin/InstaSharper#25]
Do you know + - when are ready these function ?

Thanks.

**Comment by a-legotin** [comment]
I think it will be 1.2.6, may be even 1.2.5, which I plan to release june 17

**Comment by marcelinhovt** [comment]
Nice !! And will work on Xamarin ?

**Comment by marcelinhovt** [comment]
Nice !! And will work on Xamarin ?

**Comment by a-legotin** [comment]
Yes, whatever .NET Core work

**Comment by marcelinhovt** [comment]
First of all, thanks for the nice work that you already did. 
Do you have a new preview for the direct message?

**Comment by achmstein** [comment]
It's not available yet!

**Comment by a-legotin** [comment]
yes, available in 1.3.0
