### ISSUE TITLE
Notifications???

### ISSUE THREAD

**Issue by HassanElZarkawy** [a-legotin/InstaSharper#3]
Any chance we could see the notifications end point added to InstaApi.cs soon?

**Comment by a-legotin** [comment]
Hi. What do you mean "notifications"?

**Comment by HassanElZarkawy** [comment]
Notifications end point, see who liked your photos and who started to follow you.

**Comment by a-legotin** [comment]
will be implemented at some point

**Comment by HassanElZarkawy** [comment]
got it, add this to InstaApi.cs and you're good to go.

public async Task NewsAsync()
        {
            ValidateUser();
            var newsUri = new Uri("https://i.instagram.com/api/v1/news/inbox/", UriKind.RelativeOrAbsolute);
            dynamic obj = new JObject();
            obj._uuid = _deviceInfo.DeviceGuid.ToString();
            obj._uid = _user.LoggedInUder.Pk;
            obj._csrftoken = _user.CsrfToken;
            obj.activity_module = "all";
            var body = CryptoHelper.CalculateHash(InstaApiConstants.IG_SIGNATURE_KEY, JsonConvert.SerializeObject(obj));
            var signature = $"{body}.{JsonConvert.SerializeObject(obj)}";
            var fields = new Dictionary<string, string>
            {
                {InstaApiConstants.HEADER_IG_SIGNATURE, signature},
                {InstaApiConstants.HEADER_IG_SIGNATURE_KEY_VERSION, InstaApiConstants.IG_SIGNATURE_KEY_VERSION}
            };
            var request = HttpHelper.GetDefaultRequest(HttpMethod.Post, newsUri, _deviceInfo);
            request.Content = new FormUrlEncodedContent(fields);
            var response = await _httpClient.SendAsync(request);
            var json = await response.Content.ReadAsStringAsync();
            System.Diagnostics.Debug.WriteLine(json);

            // parse json response and return it.
        }
