### ISSUE TITLE
How to get it working in wpf or WinForm solutions?

### ISSUE THREAD

**Issue by ks-troyan** [a-legotin/InstaSharper#31]
Hello, Where I can find any examples of using API in WinForm or WPF applications?

When I use API methods in console applications, everything is working just fine. 
But when I try to use it in WPF application, it freezes on login method and I can't figure out why it happens.

Am I doing something wrong?

**Comment by a-legotin** [comment]
Hi, please provide some code samples.

**Comment by verysimplenick** [comment]
> Am I doing something wrong?
Nope, author don't use `.ConfigureAwait(false)` in sync code, it's library fault, also author forgot about aggregate exceptions. But I'm too lazy for pull request. 
 @a-legotin use `.ConfigureAwait(false).GetAwaiter().GetResult();` in code and read about `SynchronizationContext` and async-await.

**Comment by ks-troyan** [comment]
@verysimplenick thanks for detailed answer, it helps me a lot to understand how async works.

I figured out that sync API methods (current implementation) in WinForms and WPF solutions work only when wrapping them into task, so there is no reason of using them.

I decided to use Async methods instead, without any changes in API code and everything works great.
