### ISSUE TITLE
who blocked user

### ISSUE THREAD

**Issue by Marjani** [a-legotin/InstaSharper#34]
Hi
how can I get users that blocked current user? is this possible?

**Comment by a-legotin** [comment]
Hello @Marjani , not yet possible. I will take into account you request, thanks.

**Comment by Marjani** [comment]
Hello @a-legotin 
Do you have plan to add this feature?

**Comment by a-legotin** [comment]
As you asking, I will have a look at implementing at in next version 1.2.6

**Comment by a-legotin** [comment]
now you can get if another user blocked you user by method `GetUserAsync(username);`
in returned object check friendship status.
