### ISSUE TITLE
Please update your Instagram app to continue

### ISSUE THREAD

**Issue by savasadar** [a-legotin/InstaSharper#4]
When I request instagram I get this error. "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram."

How can I update Instagram version?

**Comment by a-legotin** [comment]
Hello, please refer to https://github.com/mgp25/Instagram-API/wiki/Technical-information and extract you own keys

**Comment by savasadar** [comment]
I tried this way before write this issue here, But I this wiki some outdated. 

First, I tried like this gif:

http://i.imgur.com/9TWSLlq.gif

But I can't run <make> command. I got this error:

> 'make' is not recognized as an internal or external command,
operable program or batch file. 

I will try second command but I can't find GikDbg anywhere. http://www.gikir.com/ already closed.

**Comment by savasadar** [comment]
This helped me, Thanks!
