### ISSUE TITLE
How get followings list ?

### ISSUE THREAD

**Issue by Marjani** [a-legotin/InstaSharper#41]
in last version?

**Comment by a-legotin** [comment]
IInstaApi.GetUserFollowingAsync

**Comment by Marjani** [comment]
I get package  from nuget, but there isn't this function?
is possible add GetUserFollowing without Async ?

**Comment by Marjani** [comment]
How can I open source project in vs 2015? project not load.

**Comment by a-legotin** [comment]
1) there is function
2) try to use google for that ("how to run async methods synchronously")
3) use vs 2017 or visual studio code
