### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by ArefGihuni** [a-legotin/InstaSharper#43]
Here is a list of missing features for record:

- two factor authentication
- querying using id rather than username to avoid loading profile for each query to get the Id
- pagination
- accepting session data to avoid logging in every time (which may result in check-point-required)
-...

I will work on some of them when I was rich in time

**Comment by momenimohammad23** [comment]
upload multi photo & video in same post .
Edit post caption .
@a-legotin , thanks

**Comment by a-legotin** [comment]
Continued in #81 , besides that - fixed
