### ISSUE TITLE
_instaApi.GetMediaLikersAsync Not returning the full list

### ISSUE THREAD

**Issue by Sidrav** [a-legotin/InstaSharper#45]
Hi, 
I just want to congratulate you for your excellent work.

I just seem to have a problem trying to get the full list of Likers
I use the following 
var List = await _instaApi.GetMediaLikersAsync("1510066195164076297_4079771915");
The result I get is about 996  but the actual Likers are about 1200
Am I using it wrong or there is an issue?

Thank you.

**Comment by a-legotin** [comment]
not yet implemented support of full loading, will be here in 1.2.6

**Comment by Sidrav** [comment]
Thank you a-legotin  Much Appreciated

**Comment by simpleC0de** [comment]
Sorry for posting in here, but 1.2.6 sounds very interesting so far.
Any ETA?

**Comment by a-legotin** [comment]
Milestone 1.2.6 ends 14 Aug, so +- this date

**Comment by a-legotin** [comment]
Currently instagram send only first 1000 likers, didnt see any workaround for now, postpone it
