### ISSUE TITLE
Scraping seperate pages

### ISSUE THREAD

**Issue by Paardopwheels** [a-legotin/InstaSharper#58]
Will there be a feature to scrape seperate pages of followers, likers, etc. in 1.2.6? For example scraping page 5 to page 7, so not always starting to scrape at page 1. Thanks!

**Comment by a-legotin** [comment]
@Paardopwheels , yea thats good idea, I considering to use max_id for this purpose in next versions, I think it will be suitable for you as well.

**Comment by a-legotin** [comment]
Continued in #81
