### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by beljk** [a-legotin/InstaSharper#60]
i have problem in load the project
i used VS2013 and after upload the solution i get this error

F:\Projects\Webistes\Instagram\dot net\InstaSharper-develop\InstaSharper-develop\InstaSharper\InstaSharper.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  F:\Projects\Webistes\Instagram\dot net\InstaSharper-develop\InstaSharper-develop\InstaSharper\InstaSharper.csproj

F:\Projects\Webistes\Instagram\dot net\InstaSharper-develop\InstaSharper-develop\InstaSharper.Tests\InstaSharper.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  F:\Projects\Webistes\Instagram\dot net\InstaSharper-develop\InstaSharper-develop\InstaSharper.Tests\InstaSharper.Tests.csproj

**Comment by a-legotin** [comment]
upgrade to vs2017

**Comment by beljk** [comment]
yes i checked it now , Thanks for helping ;)
