### ISSUE TITLE
user must be authenticated When Login () is executed

### ISSUE THREAD

**Issue by fan92rus** [a-legotin/InstaSharper#63]
user must be authenticated When Login () is executed

**Comment by a-legotin** [comment]
@fan92rus please more details, sample project? Not able to reproduce.

**Comment by fan92rus** [comment]
account for testing: WaidXadacaedah1755:TGHe8g3oza|185.127.24.192:30973:fan92rus:65365 this account worked from browser and not worked from soft..
code
            try
            {
                Api.Login();
                Api.GetCurrentUser();
                return new Result(true);
            }
            catch (Exception ex)
            {
                return new Result(false, ex.InnerException.Message);
            }
this exception appear also in any action

**Comment by a-legotin** [comment]
I see you are using old version, try to upgrade to latest

**Comment by fan92rus** [comment]
public async Task<Result> TestAuth()
        {
            try
            {
               await Api.GetCurrentUserAsync();
                return new Result(true);
            }
            catch (Exception ex)
            {
                return new Result(false, ex.InnerException.Message);
            }
        }
nothing changed

**Comment by fan92rus** [comment]
![screenshot_7](https://user-images.githubusercontent.com/13201333/29861217-b60fc9ee-8d92-11e7-888f-b9e5829e8d64.png)

**Comment by a-legotin** [comment]
you account didnt work, my test one working just fine

**Comment by fan92rus** [comment]
i'm don't understand you, my accounts not worked? please give your source code.

**Comment by fan92rus** [comment]
i'm change IsUserAutentificated feald for public set and if accounts autorised and IsUserautentificatin = false, i'm chenge value on true, accounts started to work

**Comment by a-legotin** [comment]
Same "issue" reported in #65 , please have a look for proper solution.
