### ISSUE TITLE
Direct Thread to send a Direct Message

### ISSUE THREAD

**Issue by marcelinhovt** [a-legotin/InstaSharper#64]
Hello, thanks for your big work.

The instagram website doesn´t provide the endpoint to Send Direct... 
Looking your code and anothers ones, i understand that i need to send a thread_id as parameter to send direct... Your code get this GET_DIRECT_THREAD . 
But i don´t understand how this works. I am using xamarin.auth to post comments, likes and get somes datas. I would like to know wich parameters do i have to pass to obtain the thread_id ? Your code is too hard for me...

This is to obtain the thread_id, wright ? https://api.instagram.com/api/v1/direct_v2/threads/

And this is to send direct message ? https://api.instagram.com/api/v1/direct_v2/threads/broadcast/text/

Wich parameters do i have to send at them ?

I appreciate a lot if you or someone here help me... and i will donate for your hard work...

Thanks!

**Comment by a-legotin** [comment]
@marcelinhovt using my project you can get inbox thread by using `IInstaApi..GetDirectInboxAsync() `method it will return inbox thread, then you can find `InstaDirectInboxThread.ThreadId` property - this is what you need.

**Comment by marcelinhovt** [comment]
This AndroidDevice deviceInfo that you pass, can be a deviceinfo from ios or android, if i calling from a mobile client, wright ? Its the same as Guuid ?

**Comment by a-legotin** [comment]
@marcelinhovt yes, currently I use only android devices, didnt test with iOS. This is unique info about mobile device, you can pass you own info by passing custom `ApiRequestMessage ` to the API instance builder

**Comment by marcelinhovt** [comment]
Thanks for the reply. My problem is that i have a client that i am buiding
a app thats use some functions off instagram...until now, i needed likes,
comments, etc...everything from API Instagram. But they need to send a
Direct Message now...so, i think i dispend time using the official api and
maybe change. If i use this api, i have to publish as a web api e send http
requests from devices, wright?
Sorry for the stupids questions...

Thanks.

2017-08-30 15:02 GMT-03:00 Alexander Legotin <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:

**Comment by a-legotin** [comment]
@marcelinhovt Yes, you have to send from devices, but its all pre-build into my project, you dont have to care about it. Have a look at Samples project and you will see how it works.

**Comment by marcelinhovt** [comment]
I am seeing... I thought its a Api that i have to publish and make http´s
call, but i am not seeing controllers.
Its possible use all your code inside of my xamarin code and works?

2017-08-31 1:05 GMT-03:00 Alexander Legotin <notifications@github.com>:

**Comment by a-legotin** [comment]
@marcelinhovt check samples projects

**Comment by marcelinhovt** [comment]
I am testing them right now!! Very nice....
I will use soon as possible...thank you so much for patiente and time... i
will make a donation....
thank you again

2017-08-31 15:20 GMT-03:00 Alexander Legotin <notifications@github.com>:

**Comment by a-legotin** [comment]
not at all :)
