### ISSUE TITLE
user must be authenticated problem

### ISSUE THREAD

**Issue by mou3ad15** [a-legotin/InstaSharper#65]
hey bro, 
I thank you deeply for your work it's just great
well i'm using your 1.2.6 version, after I login and I try to do anything function like get my followers list or anything it show me "user must be authenticated" problem 
I tried after login and see IsUserAuthenticated value it shows as false

**Comment by a-legotin** [comment]
Hey @mou3ad15 looks to be the same issue #63 
You guys either dont understand how to work with async code or something wrong with your insta accounts. If you got sentry block, check wiki FAQ page, where is explained how to fix that problem.
Before posting issues try to have a look into [samples project](https://github.com/a-legotin/InstaSharper/tree/develop/InstaSharper.Examples), it may help a lot.
Please examine my code, which is perfectly works with latest version from [myget feed](https://www.myget.org/feed/Details/instasharper-develop):

`
class Program
    {
        private static IInstaApi _instaApi;

        private static void Main(string[] args)
        {
            var result = Task.Run(MainAsync).GetAwaiter().GetResult();
        }

        public static async Task<bool> MainAsync()
        {
            try
            {
                var userSession = new UserSessionData
                {
                    UserName = "user",
                    Password = "pass"
                };

                _instaApi = new InstaApiBuilder()
                    .SetUser(userSession)
                    .Build();

                Console.WriteLine($"Logging in as {userSession.UserName}");
                var logInResult = await _instaApi.LoginAsync();
                if (!logInResult.Succeeded)
                {
                    Console.WriteLine($"Unable to login: {logInResult.Info.Message}");
                }
                else
                {
                    var currentUser = await _instaApi.GetCurrentUserAsync();
                    Console.WriteLine($"Logged in: username - {currentUser.Value.UserName}, full name - {currentUser.Value.FullName}");
                    Console.WriteLine("Done. Press esc key to exit...");
                    var key = Console.ReadKey();
                    return key.Key == ConsoleKey.Escape;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            finally
            {
                var logoutResult = Task.Run(() => _instaApi.LogoutAsync()).GetAwaiter().GetResult();
                if (logoutResult.Succeeded) Console.WriteLine("Logout succeed");
            }
            return false;
        }    
    }
`
