### ISSUE TITLE
UserCredentials username and password doubt

### ISSUE THREAD

**Issue by marcelinhovt** [a-legotin/InstaSharper#67]
1) Looking your code, i have to Put the username and password directly. Using this wrapper, will not use the instagram login screen ? I mean...the user will have to tell me the password and username directly ? Do i have another option if yes?
2) In Instagram official API i cannot set Like or get friend info if his account is private. With this, can i ?

Thanks a lot.

**Comment by a-legotin** [comment]
1. No, you have to specify details directly.
2. You cannot get info if you not allowed to do that, of course.
