### ISSUE TITLE
Sending comment problem

### ISSUE THREAD

**Issue by Barbiansoft** [a-legotin/InstaSharper#68]
Hello

I try to send comment to a post via this code.:

`var commentResult = await _instaApi.CommentMediaAsync(mediaId, "Wow Nice Pi");`

But i got "HTTP/1.1 500 Internal Server Error"

Anybody can help me, what is the problem?

**Comment by a-legotin** [comment]
@Barbiansoft would you be able to provide Result state? Stack trace? Sample project?

**Comment by Barbiansoft** [comment]
Hello, thank you your response.

I dodn't gert any exception, or error message. I got FALSE Result, and i can see in Fiddler, the problem.

My code is the next.:

`private void button1_Click(object sender, EventArgs e)
        {

            figyelo = 0;

            sendlogin();            

            while(figyelo == 0)
            {
                waiter(2);
            }


            // sendphoto();

            //long userId = 296565714;
            //followuser(userId);

            //string mediaId = "1598079893371122430";
            //likepost(mediaId);
            //id=1603749964373100191
            string mediaId = "1607218536929071341";
            commentpost(mediaId);


            while (figyelo == 1)
            {
                waiter(2);
            }
            

            MessageBox.Show("hah");

        }


        public async void commentpost(string mediaId)
        {
            var commentResult = await _instaApi.CommentMediaAsync(mediaId, "Wow Nice Pi");
            
           //var followResult = await _instaApi.FollowUserAsync(userId);
           figyelo = 2;
        }


        public async void likepost(string mediaId)
        {
            var likeResult = await _instaApi.LikeMediaAsync(mediaId);
            //var followResult = await _instaApi.FollowUserAsync(userId);
            figyelo = 2;

			}        

        public async void sendlogin()
        {

            
            var userSession = new UserSessionData
            {
                UserName = *************,
                Password = *************
            };           

            _instaApi = new InstaApiBuilder().SetUser(userSession).Build();

            IResult<bool> loggedIn = await _instaApi.LoginAsync();

            figyelo = 1;

        }    `


I just want add info, likemedia, followuser and others are working.

**Comment by a-legotin** [comment]
@Barbiansoft please provide Result state, there are some fields inside.

**Comment by Barbiansoft** [comment]
Hello

Thank you your answer.

Sorry, but i don't know where can i find this Result State, or how can i get it.

**Comment by a-legotin** [comment]
`var commentResult = await _instaApi.CommentMediaAsync(mediaId, "Wow Nice Pi");`

commentResult - this is what I need.
Btw, I not able to reproduce issue. Closed.
