### ISSUE TITLE
Sudden login error

### ISSUE THREAD

**Issue by Beefaloaf** [a-legotin/InstaSharper#7]
Hello, do you know what causes this and how to fix it?

**Upon executing this code:**

`                var logInResult = _instaApi.Login();
                if (!logInResult.Succeeded) { Console.WriteLine($"Unable to login: {logInResult.Info.Message}"); }`

**I'm all of a sudden getting this response:**

`Sorry, there was a problem with your request.`

I can log in via a browser just fine.
If I move my bot to another machine, it works fine.

My bot logs in every 5 minutes, checks for new pictures, an logs out.  Did I get my bot server blacklisted or something?

**Comment by ewwink** [comment]
maybe your IP is blacklisted because too many login, you need to check and create persistent session function so no need to relogin if already logged in.

**Comment by a-legotin** [comment]
Hello @Beefaloaf , most likely @ewwink  is correct and you got banned by IP

**Comment by Beefaloaf** [comment]
That's what I was afraid of.
I'll resolve another host IP and modify my usage of InstaSharper to remain logged in.
If I remain logged in, do you know if polling `.GetUserMedia(name , 1);` every 5 minutes will be considered black-list?
Perhaps my approach at monitoring for new pictures is incorrect.

At any rate, thanks for sharing this great API!

**Comment by a-legotin** [comment]
@Beefaloaf , it depends on how many requests you are sending. Amount of requests is limited, try to minimize it. Btw API is still under development and if you will notice any issues feel free to create here.
