### ISSUE TITLE
InstaUser#InstaIdentifier returns 0, always.

### ISSUE THREAD

**Issue by simpleC0de** [a-legotin/InstaSharper#71]
The user object returns 0 for that, so its impossible to follow.
I don't know if it's just for me. Using 1.2.5, i know that 1.2.6 is released.

I created a small method to get the userId, not the best, but working:

      private long getUserId(string userName)
           {

            WebClient client = new WebClient();

            string content = client.DownloadString("https://www.instagram.com/"+userName+"/?__a=1");

            string mediaId = "";

            string[] splitUp = content.Split(new string[] { " " }, StringSplitOptions.None);
            bool b = false;
            foreach(string s in splitUp)
            {
                if (s == "\"id\":")
                {
                    b = true;
                }

                if (b &&  s != "\"id\":")
                {
                    mediaId = s;
                    break;
                }

            }

            mediaId = mediaId.Replace("\"", "");
            mediaId = mediaId.Replace(",", "");

            

            return long.Parse(mediaId);

        }

**Comment by a-legotin** [comment]
fixed in 1.3.0
