### ISSUE TITLE
Even after login isAuthenticated remains false ?

### ISSUE THREAD

**Issue by EezeSolutions** [a-legotin/InstaSharper#76]
I am having an issue i use this to login and it works fine i get logged in but  **IsUserAuthenticated** remains false due to which i cannot use the searchTag function later.

 ```
 var logInResult = _instaApi.LoginAsync();

                logInResult.Wait();

                if (!logInResult.Result.Succeeded)
                {
                    Console.WriteLine("Unable to login: {logInResult.Info.Message}");
                    return false;
                }
                else
                {
                    //im AN HERE STILL _instaApi.IsAuthenticate is false
                    return true;
                }

```
thank you

**Comment by a-legotin** [comment]
Seems something wrong with your account, can you paste Result.Info property here?

**Comment by EezeSolutions** [comment]
![screenshot 2017-10-25 14 35 28](https://user-images.githubusercontent.com/17122621/31991254-c53837a6-b990-11e7-9916-e2b1c572c0e2.png)

**Comment by a-legotin** [comment]
@EezeSolutions , not reproducible for me, try to upgrade to latest develop version (check readme) and see if its helpss, otherwise - use another account.

**Comment by EezeSolutions** [comment]
I did upgraded to the latest one :) here ... will check with another account now.
