### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by n0ise9914** [a-legotin/InstaSharper#77]
Hi bro, i'v issue with pagination, whole functions are fetching whole data and causing app to hang or crash.
for example calling GetUserFollowersAsync is fetching whole users, even maxPages not working.
Are you going to implement pagination?
i tried to sniff instagram via root certificate but it detected the fake ssl certificate and closed connection.
i also saw mgp25's repo (not tested yet), could get used as reference?

I'm going to fork this repo to help & contribute but need a bit more info
i'm sure i can sniff instagram app via an iphone, we'v one in home, but waiting for your replay.

**Comment by n0ise9914** [comment]
I saw you have implemented NextMaxId in functions but why didn't you make separate function to fetch data depend on NextMaxId, then use it for example in GetUserFollowingAsync
is it really needed to fetch whole pages in a loop? how about account with more than 100K followings?

**Comment by a-legotin** [comment]
Pagination approach will be improved in next versions, doesnt worth any discussions here

**Comment by a-legotin** [comment]
Just  checked and pagination works just fine, which means you do it wrong. Check samples folder.
