### ISSUE TITLE
GetUserFollowersAsync load only ~7500

### ISSUE THREAD

**Issue by testcszarp** [a-legotin/InstaSharper#83]
When I use GetUserFollowersAsync("username", 100) I get 7500 followers, the account have 25k followers why I can't load all folowers?

**Comment by a-legotin** [comment]
Specify more pages to load to get more followers

**Comment by testcszarp** [comment]
if I specify 500 or 1000 pages I have the same result ~7500 followers

**Comment by a-legotin** [comment]
@testcszarp , in this case follow [this article ](https://github.com/a-legotin/InstaSharper/wiki/Creating-issues-guideline-(template)) and provide more details on your problem, otherwise I cannot see any issue because its working just fine in latest version for me.

**Comment by achmstein** [comment]
I have the same issue. Result contains ~7500 followers

**Comment by a-legotin** [comment]
@achmstein , try to set request delay, provide debug log. I dont have such issues.

**Comment by achmstein** [comment]
Request response is:
`{"big_list": false, "page_size": 200, "status": "ok", "users": [...]}

I think it returns incomplete results becasuse big_list equals false
`if (!followersResponse.Value.IsBigList) return Result.Success(followers);`

**Comment by a-legotin** [comment]
@achmstein , ok will check that, please provide username for which this happens

**Comment by achmstein** [comment]
Username: @gunsnroses

**Comment by a-legotin** [comment]
roger that

**Comment by a-legotin** [comment]
fixed in 1.3.8

**Comment by achmstein** [comment]
I installed 1.3.8 but I couldn't get more than ~7500 for @gunsNroses
