### ISSUE TITLE
Failed To Login

### ISSUE THREAD

**Issue by TrynCatchMeh** [a-legotin/InstaSharper#87]
No matter how I do this I get failed to login, Was working fine before, Now it just gives the failed login.

**Comment by a-legotin** [comment]
Try to formilize you issue accrding to that [page](https://github.com/a-legotin/InstaSharper/wiki/Creating-issues-guideline-(template))

**Comment by TrynCatchMeh** [comment]
I do apologize, Just use it for my tool and even downloaded the Github one you have which worked fine before but the new one just doesn't login.

**Comment by a-legotin** [comment]
attach sample project

**Comment by TrynCatchMeh** [comment]
I mean the example/sample project you have posted on the GIT page seem to fail as well.

**Comment by a-legotin** [comment]
check if you account got banned/sentry blocked

**Comment by TrynCatchMeh** [comment]
Nope account is fine have tried it with fresh new ones and multiple others.

**Comment by a-legotin** [comment]
not enough info for any investigations, not reproducible
closed
