### ISSUE TITLE
Error using GetUserMediaAsync(@username,1)

### ISSUE THREAD

**Issue by jashmeil** [a-legotin/InstaSharper#88]
There is an errror when using GetUserMediaAsync(@username,1) 
How to fix this?
Thanks

JsonReaderException: Unterminated string. Expected delimiter: ". Path 'items[17].device_timestamp', line 1, position 60727.

**Comment by a-legotin** [comment]
which username you use?

**Comment by jashmeil** [comment]
it's random..  error occured when we looping > 40 username..
below that.. it doesn't trigger an error.

**Comment by a-legotin** [comment]
let me know when you find out username

**Comment by a-legotin** [comment]
fixed in 1.3.8
