### ISSUE TITLE
All requests get sentry_blocked

### ISSUE THREAD

**Issue by s-o-k** [a-legotin/InstaSharper#89]
Hi!
Since today all my login requests result in a sentry block no matter what accounts I do use. 
Even fresh accounts result in a sentry_block response from API endpoint. 
Same accounts work fine when used in official app or web.

Using this code to obtain api:
```
var user =
    new UserSessionData {
        UserName = "username",
        Password = "password"
    };
var device = AndroidDeviceGenerator.GetByName(AndroidDevices.SAMSUNG_NOTE3);
var requestMessage = ApiRequestMessage.FromDevice(device);
var api = _apiBuilder
    .SetUser(user)
    .SetApiRequestMessage(requestMessage)
    .SetRequestDelay(TimeSpan.FromSeconds(2.1))
    .Build();
```
And this code to login:
```
var logInResult = await api.LoginAsync();
```

Any idea?

**Comment by a-legotin** [comment]
https://github.com/a-legotin/InstaSharper/wiki/FAQ#how-to-unblock-account-from-sentry-block

**Comment by s-o-k** [comment]
Thanks for your reply, but it's still not working (even with a new IP and a new account).

In my opinion Instagram has either 
a) found a way to detect calls to their private API using InstaSharper or 
b) has changed their API.

Don't get me wrong: I think you did a great job with InstaSharper, but now it just doesn't work anymore.
I would be very happy if you could make it work again. 
And should you need any support, I would be more than willing to help. In that case just send me a message.

**Comment by a-legotin** [comment]
Hi @s-o-k, only 2 users reported that for them library not working, I also use it and everything working just fine, which means your ideas are wring.

If you could sent me your entire project with login details I can try to help - otherwise nothing I can do about that problem.

**Comment by s-o-k** [comment]
Hi @a-legotin, 
thanks a lot for the 1.3.8 update. 
Everything is working great again. 
:thumbsup:
