### ISSUE TITLE
user must be authenticated

### ISSUE THREAD

**Issue by EhsanArio** [a-legotin/InstaSharper#90]
Based on this FAQ :

> user must be authenticated
> If you get "user must be authenticated" exception - perform Login() action so that user will be authenticated. It must be done once, authentication info have same lifetime with API instance

I performed  await _instaApi.LoginAsync(); in line 51 of InstaSharper/InstaSharper.Examples/Program.cs

But that exception still remaining

Any idea ?

**Comment by a-legotin** [comment]
Try to formilize you issue accrding to that [page](https://github.com/a-legotin/InstaSharper/wiki/Creating-issues-guideline-(template)), its not enough info to help you.
