### ISSUE TITLE
InstaApiBuilder Issue

### ISSUE THREAD

**Issue by achmstein** [a-legotin/InstaSharper#95]
There's a problem with implementing InstaApiBuilder using Singleton pattern.
If I want to use multiple instances of InstaApi, I will get the same HttpClient for all instances.

So I will be never able to use a different proxy for each InstaApi instance.

**Comment by a-legotin** [comment]
1. Do not use singletone if you need multiple instances, sounds logical, right?
2. [Update to latest](https://github.com/a-legotin/InstaSharper/blob/develop/InstaSharper/API/Builder/InstaApiBuilder.cs)
