### ISSUE TITLE
GetUserMediaAsync: Unable to get current user

### ISSUE THREAD

**Issue by Nurgunkalol** [a-legotin/InstaSharper#96]
Hello!
"await _instaApi.GetUserMediaAsync("@username")"
always returns unable to get current user.

**Comment by a-legotin** [comment]
I suggest you first read [how to create issue](https://github.com/a-legotin/InstaSharper/wiki/Creating-issues-guideline-(template)) and provide more details on this problem.

**Comment by EhsanArio** [comment]
Hi
This is screenshot :

![image](https://user-images.githubusercontent.com/7068483/33167704-ac9b57ee-d053-11e7-84f5-d241704137cf.png)

And this is log :

> Starting demo of InstaSharper project
Logging in as instashrper007
01:39 ب.ظ:      Request: https://i.instagram.com/
01:39 ب.ظ:      Response: GET https://www.instagram.com/
01:39 ب.ظ:      Content:
01:39 ب.ظ:      got html content!
01:39 ب.ظ:      Response: GET https://www.instagram.com/
01:39 ب.ظ:      Content:
01:39 ب.ظ:      got html content!
01:39 ب.ظ:      ---------------------------------------------------------------------------------------------------
01:39 ب.ظ:      Request: POST https://i.instagram.com/api/v1/accounts/login/
01:39 ب.ظ:      Headers:
01:39 ب.ظ:      Accept-Language:["en-US"]
01:39 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
01:39 ب.ظ:      X-IG-Connection-Type:["WIFI"]
01:39 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
01:39 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "3e788c61-8f5a-46f7-9ffb-a85cde8a5b39",
  "signed_body": "e0620b31c2848f028228e105bc97ec9c06a22c7b80a1fa863abb19b32b84ec11.{\"phone_id\":\"5b971484-ad0f-41fa-8886-313e9e91f5b9\",\"username\":\"instashrper007\",\"guid\":\"202d7022-3533-4450-91bd-0344112e0deb\",\"device_id\":\"android-990e7bb1e8763a29\",\"password\":\"1q!Q2w@W1\",\"login_attempt_count\":\"0\"}",
  "ig_sig_key_version": "4"
}
01:39 ب.ظ:      Response: POST https://i.instagram.com/api/v1/accounts/login/
01:39 ب.ظ:      Content:
01:39 ب.ظ:      {"logged_in_user": {"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://instagram.ftpe1-1.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true, "is_business": false, "can_see_organic_insights": false, "show_insights_terms": false, "allow_contacts_sync": false, "phone_number": "+989203227689", "country_code": 98, "national_number": 9203227689}, "status": "ok"}
Press 1 to start basic demo samples
Press 2 to start upload photo demo sample
Press 3 to start comment media demo sample
Press 4 to start stories demo sample
Press 5 to start demo with saving state of API instance
Press 6 to start messaging demo sample
1
01:39 ب.ظ:      ---------------------------------------------------------------------------------------------------
01:39 ب.ظ:      Request: POST https://i.instagram.com/api/v1/accounts/current_user?edit=true
01:39 ب.ظ:      Headers:
01:39 ب.ظ:      Accept-Language:["en-US"]
01:39 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
01:39 ب.ظ:      X-IG-Connection-Type:["WIFI"]
01:39 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
01:39 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "3e788c61-8f5a-46f7-9ffb-a85cde8a5b39"
}
01:39 ب.ظ:      Response: POST https://i.instagram.com/api/v1/accounts/current_user/?edit=true
01:39 ب.ظ:      Content:
01:39 ب.ظ:      {"user": {"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://scontent-lhr3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true, "biography": "", "external_url": "", "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "https://scontent-lhr3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"}, {"width": 640, "height": 640, "url": "https://scontent-lhr3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"}], "hd_profile_pic_url_info": {"url": "https://scontent-lhr3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "width": 150, "height": 150}, "show_conversion_edit_entry": true, "birthday": null, "phone_number": "+989203227689", "country_code": 98, "national_number": 9203227689, "gender": 3, "email": "instashrper007@gmail.com", "can_link_entities_in_bio": false, "max_num_linked_entities_in_bio": 5}, "status": "ok"}
Logged in: username - instashrper007, full name - Insta
01:39 ب.ظ:      ---------------------------------------------------------------------------------------------------
01:39 ب.ظ:      Request: GET https://i.instagram.com/api/v1/users/search?q=instashrper007
01:39 ب.ظ:      Headers:
01:39 ب.ظ:      Accept-Language:["en-US"]
01:39 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
01:39 ب.ظ:      X-IG-Connection-Type:["WIFI"]
01:39 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
01:39 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "3e788c61-8f5a-46f7-9ffb-a85cde8a5b39",
  "timezone_offset": "43200",
  "count": "1",
  "rank_token": "6462369763_5b971484-ad0f-41fa-8886-313e9e91f5b9"
}
01:40 ب.ظ:      Response: GET https://i.instagram.com/api/v1/users/search/?q=instashrper007
01:40 ب.ظ:      Content:
01:40 ب.ظ:      {"num_results": 1, "users": [{"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://scontent-sin6-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "friendship_status": {"following": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "is_verified": false, "has_anonymous_profile_picture": true, "follower_count": 1, "byline": "1 follower", "mutual_followers_count": 0.0}], "has_more": false, "rank_token": "39c6a052-d6b1-4dd7-8c23-b281ecd72263", "status": "ok"}
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at InstaSharper.API.InstaApi.<GetUserFollowersAsync>d__22.MoveNext()
Stacktrace:    at InstaSharper.API.InstaApi.<GetUserFollowersAsync>d__22.MoveNext()
Count of followers [instashrper007]:0
01:40 ب.ظ:      ---------------------------------------------------------------------------------------------------
01:40 ب.ظ:      Request: GET https://i.instagram.com/api/v1/users/search?q=instashrper007
01:40 ب.ظ:      Headers:
01:40 ب.ظ:      Accept-Language:["en-US"]
01:40 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
01:40 ب.ظ:      X-IG-Connection-Type:["WIFI"]
01:40 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
01:40 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "3e788c61-8f5a-46f7-9ffb-a85cde8a5b39",
  "timezone_offset": "43200",
  "count": "1",
  "rank_token": "6462369763_5b971484-ad0f-41fa-8886-313e9e91f5b9"
}
01:40 ب.ظ:      Response: GET https://i.instagram.com/api/v1/users/search/?q=instashrper007
01:40 ب.ظ:      Content:
01:40 ب.ظ:      {"num_results": 1, "users": [{"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "friendship_status": {"following": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "is_verified": false, "has_anonymous_profile_picture": true, "follower_count": 1, "byline": "1 follower", "mutual_followers_count": 0.0}], "has_more": false, "rank_token": "06dd55c0-30b8-4e10-8054-5136b62fea13", "status": "ok"}
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at InstaSharper.API.InstaApi.<GetUserFollowingAsync>d__23.MoveNext()
Stacktrace:    at InstaSharper.API.InstaApi.<GetUserFollowingAsync>d__23.MoveNext()
Count of following [instashrper007]:0
01:40 ب.ظ:      ---------------------------------------------------------------------------------------------------
01:40 ب.ظ:      Request: GET https://i.instagram.com/api/v1/users/search?q=instashrper007
01:40 ب.ظ:      Headers:
01:40 ب.ظ:      Accept-Language:["en-US"]
01:40 ب.ظ:      X-IG-Capabilities:["3boBAA=="]
01:40 ب.ظ:      X-IG-Connection-Type:["WIFI"]
01:40 ب.ظ:      User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
01:40 ب.ظ:      Properties:
{
  "X-Google-AD-ID": "3e788c61-8f5a-46f7-9ffb-a85cde8a5b39",
  "timezone_offset": "43200",
  "count": "1",
  "rank_token": "6462369763_5b971484-ad0f-41fa-8886-313e9e91f5b9"
}
01:40 ب.ظ:      Response: GET https://i.instagram.com/api/v1/users/search/?q=instashrper007
01:40 ب.ظ:      Content:
01:40 ب.ظ:      {"num_results": 1, "users": [{"pk": 6462369763, "username": "instashrper007", "full_name": "Insta", "is_private": false, "profile_pic_url": "https://instagram.fgyd1-1.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "friendship_status": {"following": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "is_verified": false, "has_anonymous_profile_picture": true, "follower_count": 1, "byline": "1 follower", "mutual_followers_count": 0.0}], "has_more": false, "rank_token": "a70f6d90-9733-426e-a6d0-db9cbeccd662", "status": "ok"}

**Comment by a-legotin** [comment]
fixed in 1.4.13
